### ISSUE TITLE
Internal Error When running test_lottery.py

### ISSUE THREAD

**Issue by Benakich** [PatrickAlphaC/smartcontract-lottery#56]
So i am running test_lottery.py and i keep getting an INTERNAL ERROR> Exit code: 15. I have searched so far, and the closes i have come to a solution is to see that maybe its a pytest error, but pytest erros only number 5.

Here is the error on terminal

Launching 'ganache-cli.cmd --accounts 10 --mnemonic brownie --port 8545 --hardfork istanbul'...
Terminating local RPC client...
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\_pytest\main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\_pytest\main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)       
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\_pytest\main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\_pytest\main.py", line 641, in perform_collect
INTERNALERROR>     hook.pytest_collection_finish(session=self)
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)       
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\test\managers\runner.py", line 258, in pytest_collection_finish
INTERNALERROR>     brownie.network.connect(CONFIG.argv["network"])
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\main.py", line 50, in connect
INTERNALERROR>     rpc.launch(active["cmd"], **active["cmd_settings"])
INTERNALERROR>   File "C:\Users\nairaland\.local\pipx\venvs\eth-brownie\lib\site-packages\brownie\network\rpc\__init__.py", line 95, in launch
INTERNALERROR>     raise RPCConnectionError(cmd, self.process, uri)
INTERNALERROR> brownie.exceptions.RPCConnectionError: Able to launch RPC client, but unable to connect.
INTERNALERROR>
INTERNALERROR> Command: ganache-cli
INTERNALERROR> URI: https://eth-mainnet.alchemyapi.io/v2/AA4DF7Ythc08WbJvr2dGVhAuYNPnVsf0:8545INTERNALERROR> Exit Code: 15
![Screenshot (159)](https://user-images.githubusercontent.com/73526321/160234725-3f334f01-cd4f-44f8-9648-4825dc245a74.png)
![Screenshot (160)](https://user-images.githubusercontent.com/73526321/160234727-67061511-94a1-4d71-b5fa-0ddb47f5f38b.png)

**Comment by Benakich** [comment]
Never mind, didn't add the host.
