### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by DjToMeK30** [PatrickAlphaC/smartcontract-lottery#66]
Hello

Does anyone have this strange 

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 485: character maps to <undefined>

errors while running test_lottery_unit.py?

I don't get why this would happen. Maybe some problem with version of some module?

``` =========================================================================== test session starts ===========================================================================
platform win32 -- Python 3.10.2, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: D:\solidity\smartcontract-lottery
plugins: eth-brownie-1.17.2, web3-5.25.0, xdist-1.34.0, forked-1.3.0, hypothesis-6.27.3
collected 5 items / 4 deselected / 1 selected

Launching 'ganache-cli.cmd --accounts 10 --hardfork istanbul --gasLimit 12000000 --mnemonic brownie --port 8545'...

tests\test_lottery_unit.py .
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pytest-6.2.5-py3.10.egg\_pytest\main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pytest-6.2.5-py3.10.egg\_pytest\main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pytest-6.2.5-py3.10.egg\_pytest\main.py", line 348, in pytest_runtestloop    
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pytest-6.2.5-py3.10.egg\_pytest\runner.py", line 109, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pytest-6.2.5-py3.10.egg\_pytest\runner.py", line 127, in runtestprotocol     
INTERNALERROR>     reports.append(call_and_report(item, "teardown", log, nextitem=nextitem))
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pytest-6.2.5-py3.10.egg\_pytest\runner.py", line 219, in call_and_report     
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\tomi\appdata\local\programs\python\python310\lib\site-packages\pluggy-1.0.0-py3.10.egg\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Users\Tomi\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_brownie-1.17.2-py3.10.egg\brownie\test\managers\runner.py", line 362, in 
pytest_runtest_logreport
INTERNALERROR>     "sha1": self._get_hash(path),
INTERNALERROR>   File "C:\Users\Tomi\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_brownie-1.17.2-py3.10.egg\brownie\test\managers\base.py", line 91, in _get_hash
INTERNALERROR>     hash_ = _get_ast_hash(self.project_path.joinpath(path))
INTERNALERROR>   File "C:\Users\Tomi\AppData\Local\Programs\Python\Python310\lib\site-packages\eth_brownie-1.17.2-py3.10.egg\brownie\project\scripts.py", line 175, in _get_ast_hash
INTERNALERROR>     ast_list.append(ast.parse(fp.read(), origin))
INTERNALERROR>   File "C:\Users\Tomi\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
INTERNALERROR>     return codecs.charmap_decode(input,self.errors,decoding_table)[0]
INTERNALERROR> UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 485: character maps to <undefined> ```

**Comment by Aviksaikat** [comment]
I had the same issue. I  removed my brownie installation using ` pip3 uninstall eth-brownie` & removed all packages named brownie. Then I followed [this](https://github.com/microsoft/nodejs-guidelines) to properly install `nodejs`. I think  the problem lies in the c++ libraries for node. To solve this I had to download all the visual studio packages & libraries(around 10 gb). After that I installed `nodejs`, `ganache-cli`, `brownie` all from sources(except nodejs). I think the main problem is that windows is not able to run `ganache-cli` properly. 

Hey, I may be completely wrong but this is how I resolved my issue I hope it solves yours also.

**Comment by DjToMeK30** [comment]
@Aviksaikat thank you. Have not tried this because it seems alot of work for now
The code still works as it seems. The problem is only this "warning". So I will just leave it as it is for now. But thank you! :)

**Comment by DjToMeK30** [comment]
I solved this issue
Now it was even showing error on compile so I had to do something

This worked
https://www.java.com/en/download/help/locale.html

So setting ocale to my language and clicking on Beta: UFT-8 option.
![image](https://user-images.githubusercontent.com/67362243/173251682-3d88e88a-03f8-474d-a468-72a811a93ae6.png)


Now there is no warnings or erros!
